import Wrapper from "@/components/Wrapper";
import { ReduxProviders } from "@/redux/providers";
import ThemeRegistry from "@/theme/themeRegistry";
import "./globals.css";

export const metadata = {
  title: "SH-User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProviders>
        <ThemeRegistry>
          <body>
            <Wrapper>{children} </Wrapper>
          </body>
        </ThemeRegistry>
      </ReduxProviders>
    </html>
  );
}
