import Wrapper from "@/components/Wrapper";
import { ReduxProviders } from "@/redux/providers";
import ThemeRegistry from "@/theme/themeRegistry";
import "./globals.css";
import { AuthProvider } from "@/components/globals/Providers";

export const metadata = {
  title: "SH-User",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <ReduxProviders>
          <ThemeRegistry>
            <body>
              <Wrapper>{children} </Wrapper>
            </body>
          </ThemeRegistry>
        </ReduxProviders>
      </AuthProvider>
    </html>
  );
}
